/**
 * App config from environment (EXPO_PUBLIC_*).
 * Values come from apps/mobile/.env (generated by ./scripts/gen-env.sh from Terraform outputs).
 */

const getEnv = (key: string): string => {
  const value = process.env[key];
  if (value === undefined || value === '') {
    if (__DEV__) {
      console.warn(`[env] Missing or empty: ${key}. Run ./scripts/gen-env.sh to generate .env from Terraform outputs.`);
    }
    return '';
  }
  return value;
};

export const env = {
  apiBaseUrl: getEnv('EXPO_PUBLIC_API_BASE_URL').replace(/\/$/, ''),
  cognito: {
    userPoolId: getEnv('EXPO_PUBLIC_COGNITO_USER_POOL_ID'),
    clientId: getEnv('EXPO_PUBLIC_COGNITO_CLIENT_ID'),
    region: getEnv('EXPO_PUBLIC_COGNITO_REGION') || 'eu-north-1',
    hostedUiUrl: getEnv('EXPO_PUBLIC_COGNITO_HOSTED_UI_URL') || '',
  },
} as const;
