# Write apps/mobile/.env from Terraform outputs so the mobile app has current
# API and Cognito config after every terraform apply. Also updated by scripts/gen-env.sh.

resource "local_file" "mobile_env" {
  filename = "${path.module}/../../apps/mobile/.env"
  content  = <<-EOT
# Auto-generated by Terraform (mobile_env.tf). Do not commit.
EXPO_PUBLIC_API_BASE_URL=${aws_apigatewayv2_api.main.api_endpoint}
EXPO_PUBLIC_COGNITO_USER_POOL_ID=${aws_cognito_user_pool.main.id}
EXPO_PUBLIC_COGNITO_CLIENT_ID=${aws_cognito_user_pool_client.main.id}
EXPO_PUBLIC_COGNITO_REGION=eu-north-1
EOT
}
