#!/usr/bin/env bash
# Writes apps/mobile/.env from Terraform outputs (infra/terraform).
# Terraform also writes this file on apply (infra/terraform/mobile_env.tf). This script is a fallback when Terraform is not run.
# Run from repo root, or before mobile app start (see apps/mobile/package.json).
set -e
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT/infra/terraform"

API_BASE_URL=$(terraform output -raw api_base_url)
COGNITO_USER_POOL_ID=$(terraform output -raw cognito_user_pool_id)
COGNITO_CLIENT_ID=$(terraform output -raw cognito_app_client_id)
COGNITO_REGION="eu-north-1"

ENV_FILE="$REPO_ROOT/apps/mobile/.env"
cat > "$ENV_FILE" << EOF
# Auto-generated by scripts/gen-env.sh from Terraform outputs. Do not commit.
EXPO_PUBLIC_API_BASE_URL=$API_BASE_URL
EXPO_PUBLIC_COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID
EXPO_PUBLIC_COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
EXPO_PUBLIC_COGNITO_REGION=$COGNITO_REGION
EOF
