#!/usr/bin/env bash
# Writes apps/web/.env from Terraform outputs (player + admin).
# Run from repo root. Requires player and admin Terraform applied.
set -e
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

cd "$REPO_ROOT/infra/terraform"
COGNITO_USER_POOL_ID=$(terraform output -raw cognito_user_pool_id)
COGNITO_HOSTED_UI_PREFIX=$(terraform output -raw cognito_hosted_ui_domain)

cd "$REPO_ROOT/infra/terraform_admin"
ADMIN_API_URL=$(terraform output -raw admin_api_url)
ADMIN_COGNITO_CLIENT_ID=$(terraform output -raw admin_cognito_client_id)

COGNITO_REGION="eu-north-1"
ENV_FILE="$REPO_ROOT/apps/web/.env"
cat > "$ENV_FILE" << EOF
# Auto-generated by scripts/gen-env-admin-web.sh from Terraform outputs. Do not commit.
VITE_ADMIN_API_URL=$ADMIN_API_URL
VITE_COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID
VITE_COGNITO_CLIENT_ID=$ADMIN_COGNITO_CLIENT_ID
VITE_COGNITO_REGION=$COGNITO_REGION
VITE_COGNITO_HOSTED_UI_PREFIX=$COGNITO_HOSTED_UI_PREFIX
EOF
